version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/and_backend_2024
hooks:
  AfterInstall:
    - location: scripts/after_install
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/application_stop
      timeout: 300
      runas: ubuntu
 