#!/bin/bash
set -e
FOLDER="/var/www/html/express-app"
sudo chown -R ubuntu:ubuntu $FOLDER
cd $FOLDER
 
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
 
pm2 flush "express-app"
pm2 stop "express-app"
pm2 delete "express-app"