name: Deploy Express App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install -y awscli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Zip Code and Upload to S3
        run: |
          zip -r deploy.zip . -x "*.git*"
          aws s3 cp deploy.zip s3://express-app-deployment/deploy.zip

      - name: Deploy to EC2 using CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name express-app \
            --deployment-group-name express-deployment-group \
            --s3-location bucket=express-app-deployment,key=deploy.zip,bundleType=zip
